[project]
name = "eas-same-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easgen>=0.1.9",
    "pydub>=0.25.1",
    "scipy>=1.16.1",
]
